Release 1.0.0
emmanuelallan/rails_recipe pull request #18
Opened 2022-07-29 18:57 UTC by maxthestranger

2022-07-29 23:09 UTC, EricMbouwe requested changes
Hi @team, 

Good job so far 🔥!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🔥🎉
- Linters ✔
- Overall styles ✔
- Use of partials ✔
- Use of srong parameters ✔
- Foreign keys have indexes ✔
- Good tests coverage ✔
- Almost all features are working ✔👏

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 23:09 UTC, EricMbouwe commented on README.md
> +  `git checkout process-data`
- [x] Those are not the current project info. Let's fix that

2022-07-29 23:09 UTC, EricMbouwe commented on app/views/foods/index.html.erb
> +  <% end %>
- [x] The presence of this` add food` button even when there is no logged-in user causes a bug because the create food fails. Let's fix that

![no-curr-user](https://user-images.githubusercontent.com/40503704/181854875-f437c5fd-c878-486e-83c1-dd1e7204c05d.PNG)

2022-07-30 06:47 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @maxthestranger  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 06:47 UTC, merged